// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: p2p/chain/chain.proto

package chain

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/gogo/protobuf/types"

import bytes "bytes"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Message_Type int32

const (
	Message_CHAIN_STATUS      Message_Type = 0
	Message_GET_BLOCK_BODIES  Message_Type = 1
	Message_BLOCKS_BODIES     Message_Type = 2
	Message_GET_BLOCK_HEADERS Message_Type = 3
	Message_BLOCK_HEADERS     Message_Type = 4
	Message_TRANSACTIONS      Message_Type = 5
	Message_GET_RECEIPTS      Message_Type = 6
	Message_RECEIPTS          Message_Type = 7
	Message_NEW_BLOCK_HASHS   Message_Type = 8
	Message_NEW_BLOCK         Message_Type = 9
	Message_GET_BLOCKS        Message_Type = 10
	Message_BLOCKS            Message_Type = 11
)

var Message_Type_name = map[int32]string{
	0:  "CHAIN_STATUS",
	1:  "GET_BLOCK_BODIES",
	2:  "BLOCKS_BODIES",
	3:  "GET_BLOCK_HEADERS",
	4:  "BLOCK_HEADERS",
	5:  "TRANSACTIONS",
	6:  "GET_RECEIPTS",
	7:  "RECEIPTS",
	8:  "NEW_BLOCK_HASHS",
	9:  "NEW_BLOCK",
	10: "GET_BLOCKS",
	11: "BLOCKS",
}
var Message_Type_value = map[string]int32{
	"CHAIN_STATUS":      0,
	"GET_BLOCK_BODIES":  1,
	"BLOCKS_BODIES":     2,
	"GET_BLOCK_HEADERS": 3,
	"BLOCK_HEADERS":     4,
	"TRANSACTIONS":      5,
	"GET_RECEIPTS":      6,
	"RECEIPTS":          7,
	"NEW_BLOCK_HASHS":   8,
	"NEW_BLOCK":         9,
	"GET_BLOCKS":        10,
	"BLOCKS":            11,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_chain_812d25cea0114da0, []int{4, 0}
}

type ChainStatusMsg struct {
	ChainID uint64 `protobuf:"varint,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	// local total difficult
	Td                   []byte   `protobuf:"bytes,2,opt,name=td,proto3" json:"td,omitempty"`
	CurrentBlockHash     []byte   `protobuf:"bytes,3,opt,name=currentBlockHash,proto3" json:"currentBlockHash,omitempty"`
	CurrentBlockNum      uint64   `protobuf:"varint,4,opt,name=currentBlockNum,proto3" json:"currentBlockNum,omitempty"`
	GenesisBlockHash     []byte   `protobuf:"bytes,5,opt,name=genesisBlockHash,proto3" json:"genesisBlockHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainStatusMsg) Reset()      { *m = ChainStatusMsg{} }
func (*ChainStatusMsg) ProtoMessage() {}
func (*ChainStatusMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chain_812d25cea0114da0, []int{0}
}
func (m *ChainStatusMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChainStatusMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChainStatusMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ChainStatusMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainStatusMsg.Merge(dst, src)
}
func (m *ChainStatusMsg) XXX_Size() int {
	return m.Size()
}
func (m *ChainStatusMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainStatusMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ChainStatusMsg proto.InternalMessageInfo

func (m *ChainStatusMsg) GetChainID() uint64 {
	if m != nil {
		return m.ChainID
	}
	return 0
}

func (m *ChainStatusMsg) GetTd() []byte {
	if m != nil {
		return m.Td
	}
	return nil
}

func (m *ChainStatusMsg) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

func (m *ChainStatusMsg) GetCurrentBlockNum() uint64 {
	if m != nil {
		return m.CurrentBlockNum
	}
	return 0
}

func (m *ChainStatusMsg) GetGenesisBlockHash() []byte {
	if m != nil {
		return m.GenesisBlockHash
	}
	return nil
}

type GetBlockHeadersMsg struct {
	StartNum             uint64   `protobuf:"varint,1,opt,name=startNum,proto3" json:"startNum,omitempty"`
	StartHash            []byte   `protobuf:"bytes,2,opt,name=startHash,proto3" json:"startHash,omitempty"`
	Amount               uint64   `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Skip                 uint64   `protobuf:"varint,4,opt,name=skip,proto3" json:"skip,omitempty"`
	Reverse              bool     `protobuf:"varint,5,opt,name=reverse,proto3" json:"reverse,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockHeadersMsg) Reset()      { *m = GetBlockHeadersMsg{} }
func (*GetBlockHeadersMsg) ProtoMessage() {}
func (*GetBlockHeadersMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chain_812d25cea0114da0, []int{1}
}
func (m *GetBlockHeadersMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlockHeadersMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlockHeadersMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetBlockHeadersMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockHeadersMsg.Merge(dst, src)
}
func (m *GetBlockHeadersMsg) XXX_Size() int {
	return m.Size()
}
func (m *GetBlockHeadersMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockHeadersMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockHeadersMsg proto.InternalMessageInfo

func (m *GetBlockHeadersMsg) GetStartNum() uint64 {
	if m != nil {
		return m.StartNum
	}
	return 0
}

func (m *GetBlockHeadersMsg) GetStartHash() []byte {
	if m != nil {
		return m.StartHash
	}
	return nil
}

func (m *GetBlockHeadersMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetBlockHeadersMsg) GetSkip() uint64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *GetBlockHeadersMsg) GetReverse() bool {
	if m != nil {
		return m.Reverse
	}
	return false
}

type GetBlocksMsg struct {
	StartNum             uint64   `protobuf:"varint,1,opt,name=startNum,proto3" json:"startNum,omitempty"`
	Amount               uint64   `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlocksMsg) Reset()      { *m = GetBlocksMsg{} }
func (*GetBlocksMsg) ProtoMessage() {}
func (*GetBlocksMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chain_812d25cea0114da0, []int{2}
}
func (m *GetBlocksMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetBlocksMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetBlocksMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *GetBlocksMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlocksMsg.Merge(dst, src)
}
func (m *GetBlocksMsg) XXX_Size() int {
	return m.Size()
}
func (m *GetBlocksMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlocksMsg.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlocksMsg proto.InternalMessageInfo

func (m *GetBlocksMsg) GetStartNum() uint64 {
	if m != nil {
		return m.StartNum
	}
	return 0
}

func (m *GetBlocksMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DataMsg struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataMsg) Reset()      { *m = DataMsg{} }
func (*DataMsg) ProtoMessage() {}
func (*DataMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_chain_812d25cea0114da0, []int{3}
}
func (m *DataMsg) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DataMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DataMsg.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *DataMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataMsg.Merge(dst, src)
}
func (m *DataMsg) XXX_Size() int {
	return m.Size()
}
func (m *DataMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_DataMsg.DiscardUnknown(m)
}

var xxx_messageInfo_DataMsg proto.InternalMessageInfo

func (m *DataMsg) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	// defines what type of message it is.
	Type Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=chain.Message_Type" json:"type,omitempty"`
	// message content
	ChainStatusMsg       *ChainStatusMsg     `protobuf:"bytes,2,opt,name=chainStatusMsg" json:"chainStatusMsg,omitempty"`
	GetBlockHeadersMsg   *GetBlockHeadersMsg `protobuf:"bytes,3,opt,name=getBlockHeadersMsg" json:"getBlockHeadersMsg,omitempty"`
	DataMsg              *DataMsg            `protobuf:"bytes,4,opt,name=dataMsg" json:"dataMsg,omitempty"`
	GetBlocksMsg         *GetBlocksMsg       `protobuf:"bytes,5,opt,name=getBlocksMsg" json:"getBlocksMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Message) Reset()      { *m = Message{} }
func (*Message) ProtoMessage() {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_chain_812d25cea0114da0, []int{4}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_CHAIN_STATUS
}

func (m *Message) GetChainStatusMsg() *ChainStatusMsg {
	if m != nil {
		return m.ChainStatusMsg
	}
	return nil
}

func (m *Message) GetGetBlockHeadersMsg() *GetBlockHeadersMsg {
	if m != nil {
		return m.GetBlockHeadersMsg
	}
	return nil
}

func (m *Message) GetDataMsg() *DataMsg {
	if m != nil {
		return m.DataMsg
	}
	return nil
}

func (m *Message) GetGetBlocksMsg() *GetBlocksMsg {
	if m != nil {
		return m.GetBlocksMsg
	}
	return nil
}

func init() {
	proto.RegisterType((*ChainStatusMsg)(nil), "chain.ChainStatusMsg")
	proto.RegisterType((*GetBlockHeadersMsg)(nil), "chain.GetBlockHeadersMsg")
	proto.RegisterType((*GetBlocksMsg)(nil), "chain.GetBlocksMsg")
	proto.RegisterType((*DataMsg)(nil), "chain.DataMsg")
	proto.RegisterType((*Message)(nil), "chain.Message")
	proto.RegisterEnum("chain.Message_Type", Message_Type_name, Message_Type_value)
}
func (this *ChainStatusMsg) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*ChainStatusMsg)
	if !ok {
		that2, ok := that.(ChainStatusMsg)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *ChainStatusMsg")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *ChainStatusMsg but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *ChainStatusMsg but is not nil && this == nil")
	}
	if this.ChainID != that1.ChainID {
		return fmt.Errorf("ChainID this(%v) Not Equal that(%v)", this.ChainID, that1.ChainID)
	}
	if !bytes.Equal(this.Td, that1.Td) {
		return fmt.Errorf("Td this(%v) Not Equal that(%v)", this.Td, that1.Td)
	}
	if !bytes.Equal(this.CurrentBlockHash, that1.CurrentBlockHash) {
		return fmt.Errorf("CurrentBlockHash this(%v) Not Equal that(%v)", this.CurrentBlockHash, that1.CurrentBlockHash)
	}
	if this.CurrentBlockNum != that1.CurrentBlockNum {
		return fmt.Errorf("CurrentBlockNum this(%v) Not Equal that(%v)", this.CurrentBlockNum, that1.CurrentBlockNum)
	}
	if !bytes.Equal(this.GenesisBlockHash, that1.GenesisBlockHash) {
		return fmt.Errorf("GenesisBlockHash this(%v) Not Equal that(%v)", this.GenesisBlockHash, that1.GenesisBlockHash)
	}
	return nil
}
func (this *ChainStatusMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ChainStatusMsg)
	if !ok {
		that2, ok := that.(ChainStatusMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.ChainID != that1.ChainID {
		return false
	}
	if !bytes.Equal(this.Td, that1.Td) {
		return false
	}
	if !bytes.Equal(this.CurrentBlockHash, that1.CurrentBlockHash) {
		return false
	}
	if this.CurrentBlockNum != that1.CurrentBlockNum {
		return false
	}
	if !bytes.Equal(this.GenesisBlockHash, that1.GenesisBlockHash) {
		return false
	}
	return true
}
func (this *GetBlockHeadersMsg) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*GetBlockHeadersMsg)
	if !ok {
		that2, ok := that.(GetBlockHeadersMsg)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *GetBlockHeadersMsg")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *GetBlockHeadersMsg but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *GetBlockHeadersMsg but is not nil && this == nil")
	}
	if this.StartNum != that1.StartNum {
		return fmt.Errorf("StartNum this(%v) Not Equal that(%v)", this.StartNum, that1.StartNum)
	}
	if !bytes.Equal(this.StartHash, that1.StartHash) {
		return fmt.Errorf("StartHash this(%v) Not Equal that(%v)", this.StartHash, that1.StartHash)
	}
	if this.Amount != that1.Amount {
		return fmt.Errorf("Amount this(%v) Not Equal that(%v)", this.Amount, that1.Amount)
	}
	if this.Skip != that1.Skip {
		return fmt.Errorf("Skip this(%v) Not Equal that(%v)", this.Skip, that1.Skip)
	}
	if this.Reverse != that1.Reverse {
		return fmt.Errorf("Reverse this(%v) Not Equal that(%v)", this.Reverse, that1.Reverse)
	}
	return nil
}
func (this *GetBlockHeadersMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetBlockHeadersMsg)
	if !ok {
		that2, ok := that.(GetBlockHeadersMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StartNum != that1.StartNum {
		return false
	}
	if !bytes.Equal(this.StartHash, that1.StartHash) {
		return false
	}
	if this.Amount != that1.Amount {
		return false
	}
	if this.Skip != that1.Skip {
		return false
	}
	if this.Reverse != that1.Reverse {
		return false
	}
	return true
}
func (this *GetBlocksMsg) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*GetBlocksMsg)
	if !ok {
		that2, ok := that.(GetBlocksMsg)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *GetBlocksMsg")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *GetBlocksMsg but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *GetBlocksMsg but is not nil && this == nil")
	}
	if this.StartNum != that1.StartNum {
		return fmt.Errorf("StartNum this(%v) Not Equal that(%v)", this.StartNum, that1.StartNum)
	}
	if this.Amount != that1.Amount {
		return fmt.Errorf("Amount this(%v) Not Equal that(%v)", this.Amount, that1.Amount)
	}
	return nil
}
func (this *GetBlocksMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*GetBlocksMsg)
	if !ok {
		that2, ok := that.(GetBlocksMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.StartNum != that1.StartNum {
		return false
	}
	if this.Amount != that1.Amount {
		return false
	}
	return true
}
func (this *DataMsg) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*DataMsg)
	if !ok {
		that2, ok := that.(DataMsg)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *DataMsg")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *DataMsg but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *DataMsg but is not nil && this == nil")
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return fmt.Errorf("Data this(%v) Not Equal that(%v)", this.Data, that1.Data)
	}
	return nil
}
func (this *DataMsg) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*DataMsg)
	if !ok {
		that2, ok := that.(DataMsg)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Data, that1.Data) {
		return false
	}
	return true
}
func (this *Message) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Message)
	if !ok {
		that2, ok := that.(Message)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Message")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Message but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Message but is not nil && this == nil")
	}
	if this.Type != that1.Type {
		return fmt.Errorf("Type this(%v) Not Equal that(%v)", this.Type, that1.Type)
	}
	if !this.ChainStatusMsg.Equal(that1.ChainStatusMsg) {
		return fmt.Errorf("ChainStatusMsg this(%v) Not Equal that(%v)", this.ChainStatusMsg, that1.ChainStatusMsg)
	}
	if !this.GetBlockHeadersMsg.Equal(that1.GetBlockHeadersMsg) {
		return fmt.Errorf("GetBlockHeadersMsg this(%v) Not Equal that(%v)", this.GetBlockHeadersMsg, that1.GetBlockHeadersMsg)
	}
	if !this.DataMsg.Equal(that1.DataMsg) {
		return fmt.Errorf("DataMsg this(%v) Not Equal that(%v)", this.DataMsg, that1.DataMsg)
	}
	if !this.GetBlocksMsg.Equal(that1.GetBlocksMsg) {
		return fmt.Errorf("GetBlocksMsg this(%v) Not Equal that(%v)", this.GetBlocksMsg, that1.GetBlocksMsg)
	}
	return nil
}
func (this *Message) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Message)
	if !ok {
		that2, ok := that.(Message)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Type != that1.Type {
		return false
	}
	if !this.ChainStatusMsg.Equal(that1.ChainStatusMsg) {
		return false
	}
	if !this.GetBlockHeadersMsg.Equal(that1.GetBlockHeadersMsg) {
		return false
	}
	if !this.DataMsg.Equal(that1.DataMsg) {
		return false
	}
	if !this.GetBlocksMsg.Equal(that1.GetBlocksMsg) {
		return false
	}
	return true
}
func (this *ChainStatusMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&chain.ChainStatusMsg{")
	s = append(s, "ChainID: "+fmt.Sprintf("%#v", this.ChainID)+",\n")
	s = append(s, "Td: "+fmt.Sprintf("%#v", this.Td)+",\n")
	s = append(s, "CurrentBlockHash: "+fmt.Sprintf("%#v", this.CurrentBlockHash)+",\n")
	s = append(s, "CurrentBlockNum: "+fmt.Sprintf("%#v", this.CurrentBlockNum)+",\n")
	s = append(s, "GenesisBlockHash: "+fmt.Sprintf("%#v", this.GenesisBlockHash)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetBlockHeadersMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&chain.GetBlockHeadersMsg{")
	s = append(s, "StartNum: "+fmt.Sprintf("%#v", this.StartNum)+",\n")
	s = append(s, "StartHash: "+fmt.Sprintf("%#v", this.StartHash)+",\n")
	s = append(s, "Amount: "+fmt.Sprintf("%#v", this.Amount)+",\n")
	s = append(s, "Skip: "+fmt.Sprintf("%#v", this.Skip)+",\n")
	s = append(s, "Reverse: "+fmt.Sprintf("%#v", this.Reverse)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *GetBlocksMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&chain.GetBlocksMsg{")
	s = append(s, "StartNum: "+fmt.Sprintf("%#v", this.StartNum)+",\n")
	s = append(s, "Amount: "+fmt.Sprintf("%#v", this.Amount)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *DataMsg) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&chain.DataMsg{")
	s = append(s, "Data: "+fmt.Sprintf("%#v", this.Data)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Message) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 9)
	s = append(s, "&chain.Message{")
	s = append(s, "Type: "+fmt.Sprintf("%#v", this.Type)+",\n")
	if this.ChainStatusMsg != nil {
		s = append(s, "ChainStatusMsg: "+fmt.Sprintf("%#v", this.ChainStatusMsg)+",\n")
	}
	if this.GetBlockHeadersMsg != nil {
		s = append(s, "GetBlockHeadersMsg: "+fmt.Sprintf("%#v", this.GetBlockHeadersMsg)+",\n")
	}
	if this.DataMsg != nil {
		s = append(s, "DataMsg: "+fmt.Sprintf("%#v", this.DataMsg)+",\n")
	}
	if this.GetBlocksMsg != nil {
		s = append(s, "GetBlocksMsg: "+fmt.Sprintf("%#v", this.GetBlocksMsg)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringChain(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *ChainStatusMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChainStatusMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.ChainID != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.ChainID))
	}
	if len(m.Td) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintChain(dAtA, i, uint64(len(m.Td)))
		i += copy(dAtA[i:], m.Td)
	}
	if len(m.CurrentBlockHash) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintChain(dAtA, i, uint64(len(m.CurrentBlockHash)))
		i += copy(dAtA[i:], m.CurrentBlockHash)
	}
	if m.CurrentBlockNum != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.CurrentBlockNum))
	}
	if len(m.GenesisBlockHash) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintChain(dAtA, i, uint64(len(m.GenesisBlockHash)))
		i += copy(dAtA[i:], m.GenesisBlockHash)
	}
	return i, nil
}

func (m *GetBlockHeadersMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlockHeadersMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StartNum != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.StartNum))
	}
	if len(m.StartHash) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintChain(dAtA, i, uint64(len(m.StartHash)))
		i += copy(dAtA[i:], m.StartHash)
	}
	if m.Amount != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.Amount))
	}
	if m.Skip != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.Skip))
	}
	if m.Reverse {
		dAtA[i] = 0x28
		i++
		if m.Reverse {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *GetBlocksMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetBlocksMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.StartNum != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.StartNum))
	}
	if m.Amount != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.Amount))
	}
	return i, nil
}

func (m *DataMsg) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DataMsg) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Data) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintChain(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	return i, nil
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Type != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.Type))
	}
	if m.ChainStatusMsg != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.ChainStatusMsg.Size()))
		n1, err := m.ChainStatusMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.GetBlockHeadersMsg != nil {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.GetBlockHeadersMsg.Size()))
		n2, err := m.GetBlockHeadersMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.DataMsg != nil {
		dAtA[i] = 0x22
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.DataMsg.Size()))
		n3, err := m.DataMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n3
	}
	if m.GetBlocksMsg != nil {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintChain(dAtA, i, uint64(m.GetBlocksMsg.Size()))
		n4, err := m.GetBlocksMsg.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	return i, nil
}

func encodeVarintChain(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ChainStatusMsg) Size() (n int) {
	var l int
	_ = l
	if m.ChainID != 0 {
		n += 1 + sovChain(uint64(m.ChainID))
	}
	l = len(m.Td)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	l = len(m.CurrentBlockHash)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.CurrentBlockNum != 0 {
		n += 1 + sovChain(uint64(m.CurrentBlockNum))
	}
	l = len(m.GenesisBlockHash)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}

func (m *GetBlockHeadersMsg) Size() (n int) {
	var l int
	_ = l
	if m.StartNum != 0 {
		n += 1 + sovChain(uint64(m.StartNum))
	}
	l = len(m.StartHash)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovChain(uint64(m.Amount))
	}
	if m.Skip != 0 {
		n += 1 + sovChain(uint64(m.Skip))
	}
	if m.Reverse {
		n += 2
	}
	return n
}

func (m *GetBlocksMsg) Size() (n int) {
	var l int
	_ = l
	if m.StartNum != 0 {
		n += 1 + sovChain(uint64(m.StartNum))
	}
	if m.Amount != 0 {
		n += 1 + sovChain(uint64(m.Amount))
	}
	return n
}

func (m *DataMsg) Size() (n int) {
	var l int
	_ = l
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}

func (m *Message) Size() (n int) {
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovChain(uint64(m.Type))
	}
	if m.ChainStatusMsg != nil {
		l = m.ChainStatusMsg.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	if m.GetBlockHeadersMsg != nil {
		l = m.GetBlockHeadersMsg.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	if m.DataMsg != nil {
		l = m.DataMsg.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	if m.GetBlocksMsg != nil {
		l = m.GetBlocksMsg.Size()
		n += 1 + l + sovChain(uint64(l))
	}
	return n
}

func sovChain(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozChain(x uint64) (n int) {
	return sovChain(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ChainStatusMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ChainStatusMsg{`,
		`ChainID:` + fmt.Sprintf("%v", this.ChainID) + `,`,
		`Td:` + fmt.Sprintf("%v", this.Td) + `,`,
		`CurrentBlockHash:` + fmt.Sprintf("%v", this.CurrentBlockHash) + `,`,
		`CurrentBlockNum:` + fmt.Sprintf("%v", this.CurrentBlockNum) + `,`,
		`GenesisBlockHash:` + fmt.Sprintf("%v", this.GenesisBlockHash) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetBlockHeadersMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetBlockHeadersMsg{`,
		`StartNum:` + fmt.Sprintf("%v", this.StartNum) + `,`,
		`StartHash:` + fmt.Sprintf("%v", this.StartHash) + `,`,
		`Amount:` + fmt.Sprintf("%v", this.Amount) + `,`,
		`Skip:` + fmt.Sprintf("%v", this.Skip) + `,`,
		`Reverse:` + fmt.Sprintf("%v", this.Reverse) + `,`,
		`}`,
	}, "")
	return s
}
func (this *GetBlocksMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&GetBlocksMsg{`,
		`StartNum:` + fmt.Sprintf("%v", this.StartNum) + `,`,
		`Amount:` + fmt.Sprintf("%v", this.Amount) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DataMsg) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DataMsg{`,
		`Data:` + fmt.Sprintf("%v", this.Data) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Message) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Message{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`ChainStatusMsg:` + strings.Replace(fmt.Sprintf("%v", this.ChainStatusMsg), "ChainStatusMsg", "ChainStatusMsg", 1) + `,`,
		`GetBlockHeadersMsg:` + strings.Replace(fmt.Sprintf("%v", this.GetBlockHeadersMsg), "GetBlockHeadersMsg", "GetBlockHeadersMsg", 1) + `,`,
		`DataMsg:` + strings.Replace(fmt.Sprintf("%v", this.DataMsg), "DataMsg", "DataMsg", 1) + `,`,
		`GetBlocksMsg:` + strings.Replace(fmt.Sprintf("%v", this.GetBlocksMsg), "GetBlocksMsg", "GetBlocksMsg", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringChain(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ChainStatusMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChainStatusMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChainStatusMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainID", wireType)
			}
			m.ChainID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainID |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Td", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Td = append(m.Td[:0], dAtA[iNdEx:postIndex]...)
			if m.Td == nil {
				m.Td = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentBlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentBlockHash = append(m.CurrentBlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CurrentBlockHash == nil {
				m.CurrentBlockHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentBlockNum", wireType)
			}
			m.CurrentBlockNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentBlockNum |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GenesisBlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GenesisBlockHash = append(m.GenesisBlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.GenesisBlockHash == nil {
				m.GenesisBlockHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlockHeadersMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlockHeadersMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlockHeadersMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartNum", wireType)
			}
			m.StartNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartNum |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartHash = append(m.StartHash[:0], dAtA[iNdEx:postIndex]...)
			if m.StartHash == nil {
				m.StartHash = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Skip", wireType)
			}
			m.Skip = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Skip |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reverse", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Reverse = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetBlocksMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetBlocksMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetBlocksMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartNum", wireType)
			}
			m.StartNum = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartNum |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DataMsg) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DataMsg: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DataMsg: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowChain
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (Message_Type(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainStatusMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChainStatusMsg == nil {
				m.ChainStatusMsg = &ChainStatusMsg{}
			}
			if err := m.ChainStatusMsg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetBlockHeadersMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GetBlockHeadersMsg == nil {
				m.GetBlockHeadersMsg = &GetBlockHeadersMsg{}
			}
			if err := m.GetBlockHeadersMsg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DataMsg == nil {
				m.DataMsg = &DataMsg{}
			}
			if err := m.DataMsg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GetBlocksMsg", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowChain
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthChain
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.GetBlocksMsg == nil {
				m.GetBlocksMsg = &GetBlocksMsg{}
			}
			if err := m.GetBlocksMsg.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipChain(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthChain
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipChain(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowChain
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowChain
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthChain
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowChain
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipChain(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthChain = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowChain   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("p2p/chain/chain.proto", fileDescriptor_chain_812d25cea0114da0) }

var fileDescriptor_chain_812d25cea0114da0 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x4e, 0xdb, 0x50,
	0x10, 0xe6, 0x05, 0x93, 0x84, 0x89, 0x09, 0x66, 0x28, 0x55, 0x40, 0xad, 0x45, 0xbd, 0x69, 0xd4,
	0x45, 0x90, 0xd2, 0x45, 0x57, 0x5d, 0xe4, 0xc7, 0x22, 0x11, 0x25, 0xa0, 0x67, 0x57, 0x2c, 0xd1,
	0x23, 0x79, 0x75, 0xa2, 0x80, 0x1d, 0xd9, 0x2f, 0x48, 0xec, 0x7a, 0x84, 0x2e, 0x7a, 0x88, 0x1e,
	0xa2, 0x07, 0xe8, 0xb2, 0xcb, 0x6e, 0x2a, 0x41, 0x7a, 0x81, 0xde, 0xa0, 0x95, 0xc7, 0x8e, 0x13,
	0xa0, 0x52, 0x37, 0xd1, 0xcc, 0x37, 0xdf, 0x7c, 0x33, 0xdf, 0x3c, 0x2b, 0xb0, 0x33, 0xa9, 0x4f,
	0x0e, 0xfa, 0x43, 0x31, 0xf2, 0x93, 0xdf, 0xda, 0x24, 0x0c, 0x54, 0x80, 0x6b, 0x94, 0xec, 0xed,
	0x7a, 0x41, 0xe0, 0x5d, 0xca, 0x03, 0x02, 0x2f, 0xa6, 0x1f, 0x0e, 0x84, 0x7f, 0x93, 0x30, 0xf6,
	0x2c, 0x2f, 0xf0, 0x82, 0x45, 0x21, 0xce, 0x28, 0xa1, 0x28, 0xe1, 0x58, 0x5f, 0x19, 0x94, 0x5b,
	0xb1, 0x90, 0xa3, 0x84, 0x9a, 0x46, 0xc7, 0x91, 0x87, 0x15, 0x28, 0x90, 0x74, 0xb7, 0x5d, 0x61,
	0xfb, 0xac, 0xaa, 0xf1, 0x79, 0x8a, 0x65, 0xc8, 0xa9, 0x41, 0x25, 0xb7, 0xcf, 0xaa, 0x3a, 0xcf,
	0xa9, 0x01, 0xbe, 0x02, 0xa3, 0x3f, 0x0d, 0x43, 0xe9, 0xab, 0xe6, 0x65, 0xd0, 0x1f, 0x77, 0x44,
	0x34, 0xac, 0xac, 0x52, 0xf5, 0x11, 0x8e, 0x55, 0xd8, 0x5c, 0xc6, 0x7a, 0xd3, 0xab, 0x8a, 0x46,
	0xea, 0x0f, 0xe1, 0x58, 0xd5, 0x93, 0xbe, 0x8c, 0x46, 0xd1, 0x42, 0x75, 0x2d, 0x51, 0x7d, 0x88,
	0x5b, 0x9f, 0x19, 0xe0, 0xa1, 0x4c, 0xc7, 0x48, 0x31, 0x90, 0x21, 0x59, 0xd8, 0x83, 0x62, 0xa4,
	0x44, 0xa8, 0xe2, 0x29, 0x89, 0x87, 0x2c, 0xc7, 0x67, 0xb0, 0x4e, 0x31, 0xe9, 0x26, 0x5e, 0x16,
	0x00, 0x3e, 0x85, 0xbc, 0xb8, 0x0a, 0xa6, 0xbe, 0x22, 0x23, 0x1a, 0x4f, 0x33, 0x44, 0xd0, 0xa2,
	0xf1, 0x68, 0x92, 0xee, 0x4c, 0x71, 0x7c, 0xa8, 0x50, 0x5e, 0xcb, 0x30, 0x92, 0xb4, 0x5f, 0x91,
	0xcf, 0x53, 0xab, 0x09, 0xfa, 0x7c, 0xab, 0xff, 0xee, 0xb3, 0x98, 0x98, 0x5b, 0x9e, 0x68, 0x3d,
	0x87, 0x42, 0x5b, 0x28, 0x11, 0xb7, 0x23, 0x68, 0x03, 0xa1, 0x04, 0xb5, 0xea, 0x9c, 0x62, 0xeb,
	0xcf, 0x2a, 0x14, 0x8e, 0x65, 0x14, 0x09, 0x4f, 0xe2, 0x4b, 0xd0, 0xd4, 0xcd, 0x44, 0x52, 0xbd,
	0x5c, 0xdf, 0xae, 0x25, 0x9f, 0x49, 0x5a, 0xad, 0xb9, 0x37, 0x13, 0xc9, 0x89, 0x80, 0x6f, 0xa1,
	0xdc, 0xbf, 0xf7, 0xd8, 0x34, 0xb3, 0x54, 0xdf, 0x49, 0x5b, 0xee, 0x7f, 0x09, 0xfc, 0x01, 0x19,
	0xbb, 0x80, 0xde, 0xa3, 0x63, 0xd3, 0xa1, 0x4a, 0xf5, 0xdd, 0x54, 0xe2, 0xf1, 0x6b, 0xf0, 0x7f,
	0x34, 0x61, 0x15, 0x0a, 0x83, 0xc4, 0x1d, 0x9d, 0xb4, 0x54, 0x2f, 0xa7, 0xfd, 0xa9, 0x67, 0x3e,
	0x2f, 0xe3, 0x1b, 0xd0, 0xbd, 0xa5, 0x5b, 0xd2, 0xa9, 0x4b, 0x99, 0xc9, 0xe5, 0x33, 0xf3, 0x7b,
	0x44, 0xeb, 0x27, 0x03, 0x2d, 0xf6, 0x8e, 0x06, 0xe8, 0xad, 0x4e, 0xa3, 0xdb, 0x3b, 0x77, 0xdc,
	0x86, 0xfb, 0xde, 0x31, 0x56, 0xf0, 0x09, 0x18, 0x87, 0xb6, 0x7b, 0xde, 0x7c, 0x77, 0xd2, 0x3a,
	0x3a, 0x6f, 0x9e, 0xb4, 0xbb, 0xb6, 0x63, 0x30, 0xdc, 0x82, 0x0d, 0x42, 0x9c, 0x39, 0x94, 0xc3,
	0x1d, 0xd8, 0x5a, 0x10, 0x3b, 0x76, 0xa3, 0x6d, 0x73, 0xc7, 0x58, 0xcd, 0x98, 0x19, 0xa4, 0xc5,
	0x43, 0x5c, 0xde, 0xe8, 0x39, 0x8d, 0x96, 0xdb, 0x3d, 0xe9, 0x39, 0xc6, 0x5a, 0x8c, 0xc4, 0xbd,
	0xdc, 0x6e, 0xd9, 0xdd, 0x53, 0xd7, 0x31, 0xf2, 0xa8, 0x43, 0x31, 0xcb, 0x0a, 0xb8, 0x0d, 0x9b,
	0x3d, 0xfb, 0x6c, 0xae, 0xdd, 0x70, 0x3a, 0x8e, 0x51, 0xc4, 0x0d, 0x58, 0xcf, 0x40, 0x63, 0x1d,
	0xcb, 0x00, 0xd9, 0x7c, 0xc7, 0x00, 0x04, 0xc8, 0xa7, 0x71, 0xa9, 0x79, 0xf6, 0xe3, 0xce, 0x5c,
	0xb9, 0xbd, 0x33, 0xd9, 0xef, 0x3b, 0x93, 0x7d, 0x9c, 0x99, 0xec, 0xcb, 0xcc, 0x64, 0xdf, 0x66,
	0x26, 0xfb, 0x3e, 0x33, 0xd9, 0xed, 0xcc, 0x64, 0x9f, 0x7e, 0x99, 0x2b, 0xf0, 0x22, 0x08, 0xbd,
	0xda, 0xc8, 0xbf, 0x1e, 0xf9, 0xb5, 0xf1, 0x78, 0xe9, 0xff, 0xa3, 0x36, 0x14, 0xfe, 0x20, 0x1a,
	0x8a, 0xb1, 0x6c, 0xea, 0x47, 0x47, 0xf4, 0xf0, 0xa7, 0x31, 0x7e, 0xca, 0x2e, 0xf2, 0x44, 0x78,
	0xfd, 0x37, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xfa, 0xca, 0x6c, 0x79, 0x04, 0x00, 0x00,
}
